sudo: false
language: ruby
rvm:
  - 2.4.0
before_install: gem install bundler -v 1.12.5 
addons:
  code_climate:
    repo_token: 04f7e10872188ec36e25d46f43d6c319a97526a3b1514cf659cd53d6e1849929
after_success:
  - bundle exec codeclimate-test-reporter
